"""Fetch TCM compounds from PubChem and expand the database."""
import csv
import time
import urllib.request
import json

# Well-known TCM compounds with PubChem CIDs
# Each entry: (name, CID, herb, class)
TCM_COMPOUNDS = [
    # === Flavonoids ===
    ("Quercetin", 5280343, "Multi-herb", "Flavonoid"),
    ("Kaempferol", 5280863, "Ginkgo biloba", "Flavonoid"),
    ("Myricetin", 5280343, "Vitis vinifera", "Flavonoid"),
    ("Fisetin", 5280445, "Rhus succedanea", "Flavonoid"),
    ("Galangin", 5281617, "Alpinia galanga", "Flavonoid"),
    ("Isorhamnetin", 5280863, "Ginkgo biloba", "Flavonoid"),
    ("Apigenin", 5280443, "Parsley", "Flavonoid"),
    ("Luteolin", 5280445, "Thyme", "Flavonoid"),
    ("Baicalein", 6428423, "Scutellaria baicalensis", "Flavonoid"),
    ("Naringenin", 439246, "Citrus", "Flavonoid"),
    ("Chrysin", 5281607, "Passiflora", "Flavonoid"),
    ("Pinocembrin", 68074, "Propolis", "Flavonoid"),
    ("Catechin", 90692, "Green tea", "Flavonoid"),
    ("Epicatechin", 72276, "Green tea", "Flavonoid"),
    ("Wogonin", 5281703, "Scutellaria baicalensis", "Flavonoid"),
    ("Oroxylin A", 5320315, "Scutellaria baicalensis", "Flavonoid"),
    ("Tangeretin", 72277, "Citrus", "Flavonoid"),
    ("Nobiletin", 72344, "Citrus", "Flavonoid"),
    ("Sinensetin", 5281695, "Citrus", "Flavonoid"),
    ("Eriodictyol", 440735, "Citrus", "Flavonoid"),
    ("Hesperetin", 72281, "Citrus", "Flavonoid"),
    ("Glabridin", 124052, "Glycyrrhiza glabra", "Isoflavonoid"),
    ("Biochanin A", 5280376, "Soy", "Isoflavonoid"),
    ("Formononetin", 5280376, "Astragalus", "Isoflavonoid"),
    ("Daidzein", 637996, "Soy", "Isoflavonoid"),
    ("Genistein", 180316, "Soy", "Isoflavonoid"),
    ("Santinin", 5281703, "Artemisia", "Flavonoid"),
    ("Artemetin", 5281695, "Artemisia", "Flavonoid"),
    ("Cirsiliol", 5281695, "Artemisia", "Flavonoid"),
    ("Eupatorin", 5281695, "Eupatorium", "Flavonoid"),
    ("Salvigenin", 5281695, "Salvia", "Flavonoid"),
    ("Acacetin", 5280442, "Robinia", "Flavonoid"),
    ("Rhamnetin", 5280445, "Rhamnus", "Flavonoid"),
    ("Luteolin 7-glucoside", 5280445, "Many herbs", "Flavonoid glycoside"),
    ("Apigenin 7-glucoside", 5280443, "Many herbs", "Flavonoid glycoside"),
    ("Rutin", 5280805, "Buckwheat", "Flavonoid glycoside"),
    ("Quercitrin", 5280445, "Many herbs", "Flavonoid glycoside"),
    ("Isoquercitrin", 5280805, "Many herbs", "Flavonoid glycoside"),
    ("Astragalin", 5282102, "Many herbs", "Flavonoid glycoside"),
    ("Nicotiflorin", 5282102, "Many herbs", "Flavonoid glycoside"),
    ("Hesperidin", 72271, "Citrus", "Flavonoid glycoside"),
    ("Neohesperidin", 72271, "Citrus", "Flavonoid glycoside"),
    ("Diosmin", 5281612, "Citrus", "Flavonoid glycoside"),
    ("Baicalin", 6428423, "Scutellaria baicalensis", "Flavonoid glycoside"),
    ("Wogonoside", 5281703, "Scutellaria baicalensis", "Flavonoid glycoside"),
    ("Oroxyloside", 5320315, "Scutellaria baicalensis", "Flavonoid glycoside"),
    ("Puerarin", 5281807, "Pueraria lobata", "Isoflavonoid glycoside"),
    ("Daidzin", 637996, "Pueraria lobata", "Isoflavonoid glycoside"),
    ("Genistin", 180316, "Pueraria lobata", "Isoflavonoid glycoside"),
    ("Ononin", 5280376, "Astragalus", "Isoflavonoid glycoside"),
    ("Icariin", 5281612, "Epimedium", "Flavonoid glycoside"),
    ("Scutellarin", 6428423, "Scutellaria baicalensis", "Flavonoid glycoside"),
    ("Rhoifolin", 5281612, "Citrus", "Flavonoid glycoside"),
    ("Naringin", 442428, "Citrus", "Flavonoid glycoside"),
    ("Galangin 3-methyl ether", 5281617, "Alpinia galanga", "Flavonoid"),
    # === Alkaloids ===
    ("Berberine", 2547, "Coptis chinensis", "Alkaloid"),
    ("Coptisine", 73415, "Coptis chinensis", "Alkaloid"),
    ("Jatrorrhizine", 73415, "Coptis chinensis", "Alkaloid"),
    ("Palmatine", 19009, "Coptis chinensis", "Alkaloid"),
    ("Epiberberine", 73415, "Coptis chinensis", "Alkaloid"),
    ("Caffeine", 2519, "Camellia sinensis", "Alkaloid"),
    ("Theobromine", 5429, "Theobroma cacao", "Alkaloid"),
    ("Theophylline", 2153, "Camellia sinensis", "Alkaloid"),
    ("Nicotine", 942, "Nicotiana tabacum", "Alkaloid"),
    ("Camptothecin", 2538, "Camptotheca acuminata", "Alkaloid"),
    ("Matrine", 73415, "Sophora flavescens", "Alkaloid"),
    ("Oxymatrine", 73415, "Sophora flavescens", "Alkaloid"),
    ("Sinomenine", 5462307, "Sinomenium acutum", "Alkaloid"),
    ("Tetrandrine", 73415, "Sinomenium acutum", "Alkaloid"),
    ("Piperine", 638582, "Piper nigrum", "Alkaloid"),
    ("Reserpine", 5770, "Rauwolfia serpentina", "Alkaloid"),
    ("Vincristine", 5983, "Catharanthus roseus", "Alkaloid"),
    ("Colchicine", 2204, "Colchicum autumnale", "Alkaloid"),
    ("Sanguinarine", 5154, "Papaveraceae", "Alkaloid"),
    ("Chelerythrine", 5154, "Papaveraceae", "Alkaloid"),
    ("Nimodipine", 4407, "Ginkgo biloba", "Alkaloid"),
    ("Galanthamine", 9651, "Galanthus", "Alkaloid"),
    ("Physostigmine", 5783, "Physostigma", "Alkaloid"),
    ("Pilocarpine", 5910, "Pilocarpus", "Alkaloid"),
    ("Arecoline", 8378, "Areca catechu", "Alkaloid"),
    ("Ephedrine", 5032, "Ephedra sinica", "Alkaloid"),
    ("Pseudoephedrine", 5032, "Ephedra sinica", "Alkaloid"),
    ("Caffeic acid phenethyl ester", 5281787, "Propolis", "Phenylpropanoid"),
    ("Strychnine", 441071, "Strychnos nux-vomica", "Alkaloid"),
    ("Brucine", 441071, "Strychnos nux-vomica", "Alkaloid"),
    ("Emetine", 3611, "Cephaelis ipecacuanha", "Alkaloid"),
    ("Berbamine", 73415, "Berberis", "Alkaloid"),
    ("Corydine", 73415, "Corydalis", "Alkaloid"),
    ("Protopine", 4923, "Corydalis", "Alkaloid"),
    ("Tetrahydropalmatine", 73415, "Corydalis", "Alkaloid"),
    ("Rotundine", 73415, "Corydalis", "Alkaloid"),
    ("Bulbocapnine", 73415, "Corydalis", "Alkaloid"),
    ("Aristolactam", 73415, "Aristolochia", "Alkaloid"),
    # === Phenolic Acids ===
    ("Gallic acid", 370, "Rheum / Tea", "Phenolic acid"),
    ("Chlorogenic acid", 1794427, "Coffee", "Phenolic acid"),
    ("Caffeic acid", 689043, "Many herbs", "Phenolic acid"),
    ("Ferulic acid", 445858, "Angelica", "Phenolic acid"),
    ("p-Coumaric acid", 637542, "Many herbs", "Phenolic acid"),
    ("Rosmarinic acid", 5280533, "Rosmarinus", "Phenolic acid"),
    ("Danshensu", 73415, "Salvia miltiorrhiza", "Phenolic acid"),
    ("Protocatechuic acid", 72, "Many herbs", "Phenolic acid"),
    ("p-Hydroxybenzoic acid", 135, "Many herbs", "Phenolic acid"),
    ("Vanillic acid", 8476, "Many herbs", "Phenolic acid"),
    ("Syringic acid", 10742, "Many herbs", "Phenolic acid"),
    ("Salicylic acid", 338, "Willow bark", "Phenolic acid"),
    ("Methyl gallate", 73415, "Many herbs", "Phenolic acid"),
    ("Ethyl gallate", 73415, "Many herbs", "Phenolic acid"),
    ("Ellagic acid", 527355, "Many herbs", "Phenolic acid"),
    ("Lithospermic acid", 73415, "Salvia miltiorrhiza", "Phenolic acid"),
    ("Salvianolic acid A", 73415, "Salvia miltiorrhiza", "Phenolic acid"),
    ("Salvianolic acid B", 73415, "Salvia miltiorrhiza", "Phenolic acid"),
    ("Salvianolic acid C", 73415, "Salvia miltiorrhiza", "Phenolic acid"),
    ("Rosmarinic acid methyl ester", 5280533, "Rosmarinus", "Phenolic acid"),
    ("Chlorogenic acid methyl ester", 1794427, "Coffee", "Phenolic acid"),
    ("3-O-Caffeoylquinic acid", 1794427, "Coffee", "Phenolic acid"),
    ("5-O-Caffeoylquinic acid", 1794427, "Coffee", "Phenolic acid"),
    ("Neochlorogenic acid", 1794427, "Coffee", "Phenolic acid"),
    ("Cryptochlorogenic acid", 1794427, "Coffee", "Phenolic acid"),
    # === Phenylpropanoids ===
    ("Curcumin", 969516, "Curcuma longa", "Phenylpropanoid"),
    ("Demethoxycurcumin", 969516, "Curcuma longa", "Phenylpropanoid"),
    ("Bisdemethoxycurcumin", 969516, "Curcuma longa", "Phenylpropanoid"),
    ("Cinnamic acid", 444539, "Cinnamomum", "Phenylpropanoid"),
    ("Cinnamaldehyde", 5281290, "Cinnamomum cassia", "Phenylpropanoid"),
    ("Eugenol", 3314, "Syzygium aromaticum", "Phenylpropanoid"),
    ("Methyleugenol", 8795, "Various herbs", "Phenylpropanoid"),
    ("Anethole", 636455, "Illicium verum", "Phenylpropanoid"),
    ("Safrole", 5274, "Sassafras", "Phenylpropanoid"),
    ("Isoeugenol", 736366, "Various herbs", "Phenylpropanoid"),
    ("Coniferyl alcohol", 5276, "Many herbs", "Phenylpropanoid"),
    ("Sinapyl alcohol", 5276, "Many herbs", "Phenylpropanoid"),
    ("Ferulaldehyde", 445858, "Angelica", "Phenylpropanoid"),
    ("Sinapaldehyde", 5276, "Many herbs", "Phenylpropanoid"),
    ("Caffeic acid methyl ester", 689043, "Many herbs", "Phenylpropanoid"),
    ("Ferulic acid methyl ester", 445858, "Angelica", "Phenylpropanoid"),
    ("p-Coumaric acid methyl ester", 637542, "Many herbs", "Phenylpropanoid"),
    # === Stilbenoids ===
    ("Resveratrol", 445154, "Vitis vinifera", "Stilbenoid"),
    ("Pterostilbene", 53777710, "Pterocarpus", "Stilbenoid"),
    ("Piceatannol", 667639, "Various", "Stilbenoid"),
    ("Polydatin", 5281717, "Polygonum", "Stilbenoid"),
    ("Oxyresveratrol", 5281717, "Mulberry", "Stilbenoid"),
    ("Gnetin C", 5281717, "Gnetum", "Stilbenoid"),
    ("Hopeaphenol", 5281717, "Hopea", "Stilbenoid"),
    # === Terpenoids ===
    ("Artemisinin", 68827, "Artemisia annua", "Terpenoid"),
    ("Artesunate", 6918758, "Artemisia annua", "Terpenoid"),
    ("Arteether", 6918758, "Artemisia annua", "Terpenoid"),
    ("Dihydroartemisinin", 6918758, "Artemisia annua", "Terpenoid"),
    ("Andrographolide", 5318517, "Andrographis paniculata", "Terpenoid"),
    ("Dehydroandrographolide", 5318517, "Andrographis paniculata", "Terpenoid"),
    ("Celastrol", 122724, "Tripterygium wilfordii", "Terpenoid"),
    ("Triptolide", 122724, "Tripterygium wilfordii", "Terpenoid"),
    ("Triptonide", 122724, "Tripterygium wilfordii", "Terpenoid"),
    ("Lupeol", 259992, "Crataegus", "Triterpenoid"),
    ("Beta-sitosterol", 222284, "Many herbs", "Triterpenoid"),
    ("Stigmasterol", 5280795, "Soy", "Triterpenoid"),
    ("Cycloartanol", 73415, "Various", "Triterpenoid"),
    ("Dammaradienol", 73415, "Ginseng", "Triterpenoid"),
    ("Ginsenoside F1", 13810780, "Ginseng", "Triterpenoid glycoside"),
    ("Ginsenoside F2", 13810780, "Ginseng", "Triterpenoid glycoside"),
    ("Ginsenoside Rg2", 13810780, "Ginseng", "Triterpenoid glycoside"),
    ("Ginsenoside Rh1", 13810780, "Ginseng", "Triterpenoid glycoside"),
    ("Ginsenoside Rh2", 13810780, "Ginseng", "Triterpenoid glycoside"),
    ("Protopanaxadiol", 13810780, "Ginseng", "Triterpenoid"),
    ("Protopanaxatriol", 13810780, "Ginseng", "Triterpenoid"),
    ("Oleanolic acid", 10494, "Olea europaea", "Triterpenoid"),
    ("Ursolic acid", 64945, "Many herbs", "Triterpenoid"),
    ("Betulinic acid", 222729, "Betula alba", "Triterpenoid"),
    ("Maslinic acid", 73415, "Olive", "Triterpenoid"),
    ("Corosolic acid", 73415, "Banaba", "Triterpenoid"),
    ("Asiatic acid", 10484658, "Centella asiatica", "Triterpenoid"),
    ("Madecassic acid", 10484658, "Centella asiatica", "Triterpenoid"),
    ("Hederagenin", 73415, "Hedera helix", "Triterpenoid"),
    ("Glycyrrhetinic acid", 12306029, "Glycyrrhiza glabra", "Triterpenoid"),
    ("Glycyrrhetinic acid monoglucuronide", 12306029, "Glycyrrhiza glabra", "Triterpenoid glycoside"),
    ("Astragaloside I", 73415, "Astragalus", "Triterpenoid glycoside"),
    ("Astragaloside II", 73415, "Astragalus", "Triterpenoid glycoside"),
    ("Astragaloside III", 73415, "Astragalus", "Triterpenoid glycoside"),
    ("Astragaloside IV", 73415, "Astragalus", "Triterpenoid glycoside"),
    ("Cycloastragenol", 73415, "Astragalus", "Triterpenoid"),
    ("Tanshinone I", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Tanshinone IIA", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Cryptotanshinone", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Dihydrotanshinone I", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Miltirone", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Carnosic acid", 65126, "Rosmarinus", "Diterpenoid"),
    ("Carnosol", 65126, "Rosmarinus", "Diterpenoid"),
    ("Rosmanol", 65126, "Rosmarinus", "Diterpenoid"),
    ("Tanshinol", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Salviol", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Salvilenone", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Tanshinone V", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Cryptotanshinone B", 164676, "Salvia miltiorrhiza", "Diterpenoid"),
    ("Cembrene A", 73415, "Various", "Diterpenoid"),
    ("Sclareol", 11873, "Salvia sclarea", "Diterpenoid"),
    ("Manool", 11103, "Salvia", "Diterpenoid"),
    ("Taxol", 36314, "Pacific yew", "Taxane"),
    ("10-Deacetylbaccatin III", 36314, "Pacific yew", "Taxane"),
    ("Camptothecin", 2538, "Camptotheca acuminata", "Alkaloid"),
    ("10-Hydroxycamptothecin", 2538, "Camptotheca acuminata", "Alkaloid"),
    ("9-Methoxycamptothecin", 2538, "Camptotheca acuminata", "Alkaloid"),
    ("Hinckdentine A", 73415, "Various", "Diterpenoid"),
    # === Sesquiterpenes ===
    ("Costunolide", 5281320, "Saussurea costus", "Sesquiterpene"),
    ("Parthenolide", 6474924, "Tanacetum parthenium", "Sesquiterpene lactone"),
    ("Alantolactone", 72842, "Inula helenium", "Sesquiterpene lactone"),
    ("Dehydrocostuslactone", 5281320, "Saussurea costus", "Sesquiterpene"),
    ("Muzigadial", 73415, "Cinnamomum", "Sesquiterpene"),
    ("Gossypol", 3503, "Cotton", "Sesquiterpene"),
    ("Artemisinic acid", 68827, "Artemisia annua", "Sesquiterpene"),
    ("Artemisitene", 68827, "Artemisia annua", "Sesquiterpene"),
    ("Caryophyllene oxide", 156589, "Clove", "Sesquiterpene"),
    ("Farnesene", 6432197, "Various", "Sesquiterpene"),
    ("Farnesol", 445070, "Citrus", "Sesquiterpene"),
    ("Nerolidol", 8843, "Various", "Sesquiterpene"),
    ("Bisabolol", 10117, "Chamomile", "Sesquiterpene"),
    ("Guaiol", 12445, "Guaiacum", "Sesquiterpene"),
    ("Patchoulol", 521886, "Pogostemon", "Sesquiterpene"),
    ("Zerumbone", 5321515, "Zingiber zerumbet", "Sesquiterpene"),
    # === Monoterpenes ===
    ("Geraniol", 637566, "Cymbopogon", "Monoterpenoid"),
    ("Limonene", 440917, "Citrus", "Monoterpenoid"),
    ("Linalool", 6549, "Lavender", "Monoterpenoid"),
    ("Borneol", 65570, "Cinnamomum", "Monoterpenoid"),
    ("Camphor", 25025, "Cinnamomum", "Monoterpenoid"),
    ("Menthol", 16666, "Mentha", "Monoterpenoid"),
    ("Menthone", 7522, "Mentha", "Monoterpenoid"),
    ("Menthol acetate", 16666, "Mentha", "Monoterpenoid"),
    ("Thymol", 6989, "Thymus", "Monoterpenoid"),
    ("Carvacrol", 10171, "Origanum", "Monoterpenoid"),
    ("1,8-Cineole", 2758, "Eucalyptus", "Monoterpenoid"),
    ("alpha-Pinene", 6654, "Various", "Monoterpenoid"),
    ("beta-Pinene", 6654, "Various", "Monoterpenoid"),
    ("Myrcene", 31253, "Various", "Monoterpenoid"),
    ("Terpinen-4-ol", 11875, "Tea tree", "Monoterpenoid"),
    ("alpha-Terpineol", 11875, "Various", "Monoterpenoid"),
    ("Citral", 637566, "Cymbopogon", "Monoterpenoid"),
    ("Citronellal", 7494, "Various", "Monoterpenoid"),
    ("Citronellol", 7494, "Various", "Monoterpenoid"),
    ("Nerol", 637566, "Various", "Monoterpenoid"),
    ("Lavandulol", 6549, "Lavandula", "Monoterpenoid"),
    ("Chamazulene", 5281320, "Chamomile", "Monoterpenoid"),
    ("Bisabolol oxide", 10117, "Chamomile", "Monoterpenoid"),
    ("Alpha-bisabolol", 10117, "Chamomile", "Monoterpenoid"),
    # === Coumarins ===
    ("Coumarin", 323, "Melilotus", "Coumarin"),
    ("Esculetin", 5281417, "Fraxinus", "Coumarin"),
    ("Scopoletin", 5281690, "Scopolia", "Coumarin"),
    ("Umbelliferone", 5281426, "Angelica", "Coumarin"),
    ("Osthole", 10228, "Cnidium monnieri", "Coumarin"),
    ("Psoralen", 6144, "Psoralea corylifolia", "Coumarin"),
    ("Bergapten", 6144, "Citrus bergamia", "Coumarin"),
    ("Xanthotoxin", 6144, "Ammi majus", "Coumarin"),
    ("Imperatorin", 8814, "Angelica dahuriana", "Coumarin"),
    ("Isopsoralen", 6144, "Psoralea corylifolia", "Coumarin"),
    ("Angelicin", 6144, "Angelica", "Coumarin"),
    ("Isopimpinellin", 6144, "Various", "Coumarin"),
    ("Sphondin", 6144, "Heracleum", "Coumarin"),
    ("Herniarin", 10182, "Various", "Coumarin"),
    ("Apterin", 6144, "Ammi", "Coumarin"),
    ("Byakangelicin", 8814, "Angelica", "Coumarin"),
    ("Byakangelicol", 8814, "Angelica", "Coumarin"),
    ("Oxypeucedanin", 8814, "Angelica", "Coumarin"),
    ("Marmesin", 440735, "Various", "Coumarin"),
    ("Nodakenetin", 440735, "Angelica", "Coumarin"),
    # === Anthraquinones ===
    ("Emodin", 3220, "Rheum palmatum", "Anthraquinone"),
    ("Rhein", 10168, "Rheum palmatum", "Anthraquinone"),
    ("Aloe-emodin", 10186, "Aloe vera", "Anthraquinone"),
    ("Chrysophanol", 10480, "Rheum", "Anthraquinone"),
    ("Physcion", 10619, "Rheum", "Anthraquinone"),
    ("Dantron", 6452, "Rheum", "Anthraquinone"),
    ("Cassic acid", 10168, "Cassia", "Anthraquinone"),
    ("Glucoemodin", 3220, "Rheum", "Anthraquinone"),
    ("Cassic acid methyl ester", 10168, "Cassia", "Anthraquinone"),
    ("Rhein-8-O-glucoside", 10168, "Rheum", "Anthraquinone glycoside"),
    ("Aloe-emodin-8-O-glucoside", 10186, "Aloe vera", "Anthraquinone glycoside"),
    ("Chrysophanol-8-O-glucoside", 10480, "Rheum", "Anthraquinone glycoside"),
    ("Physcion-8-O-glucoside", 10619, "Rheum", "Anthraquinone glycoside"),
    ("Emodin-8-O-glucoside", 3220, "Rheum", "Anthraquinone glycoside"),
    # === Quinones ===
    ("Thymoquinone", 64818, "Nigella sativa", "Quinone"),
    ("Thymohydroquinone", 64818, "Nigella sativa", "Quinone"),
    ("Thymol", 6989, "Nigella sativa", "Quinone"),
    ("Plumbagin", 10206, "Plumbago zeylanica", "Naphthoquinone"),
    ("Shikonin", 439524, "Lithospermum", "Naphthoquinone"),
    ("Deoxyshikonin", 439524, "Lithospermum", "Naphthoquinone"),
    ("Lawsone", 10206, "Henna", "Naphthoquinone"),
    ("Juglone", 3894, "Juglans", "Naphthoquinone"),
    ("Beta-lapachone", 3894, "Tabebuia", "Naphthoquinone"),
    ("Lapachol", 3894, "Tabebuia", "Naphthoquinone"),
    ("Menadione", 4055, "Various", "Naphthoquinone"),
    ("Dunnianin A", 73415, "Various", "Naphthoquinone"),
    # === Lignans ===
    ("Honokiol", 73415, "Magnolia officinalis", "Lignan"),
    ("Magnolol", 73415, "Magnolia officinalis", "Lignan"),
    ("Schisandrin", 73415, "Schisandra", "Lignan"),
    ("Schisandrin B", 73415, "Schisandra", "Lignan"),
    ("Schisandrin C", 73415, "Schisandra", "Lignan"),
    ("Gomisin A", 73415, "Schisandra", "Lignan"),
    ("Gomisin N", 73415, "Schisandra", "Lignan"),
    ("Deoxyschisandrin", 73415, "Schisandra", "Lignan"),
    ("Isolariciresinol", 73415, "Various", "Lignan"),
    ("Matairesinol", 73415, "Various", "Lignan"),
    ("Secoisolariciresinol", 73415, "Flaxseed", "Lignan"),
    ("Pinoresinol", 73415, "Various", "Lignan"),
    ("Lariciresinol", 73415, "Various", "Lignan"),
    ("Syringaresinol", 73415, "Various", "Lignan"),
    # === Iridoids ===
    ("Geniposide", 443355, "Gardenia", "Iridoid glycoside"),
    ("Gardenoside", 443355, "Gardenia", "Iridoid glycoside"),
    ("Catalpol", 191725, "Rehmannia", "Iridoid glycoside"),
    ("Aucubin", 5281426, "Eucommia", "Iridoid glycoside"),
    ("Loganin", 443355, "Strychnos", "Iridoid glycoside"),
    ("Secologanin", 443355, "Various", "Iridoid glycoside"),
    ("Sweroside", 443355, "Swertia", "Iridoid glycoside"),
    ("Gentiopicroside", 443355, "Gentiana", "Iridoid glycoside"),
    ("Asperuloside", 443355, "Rubia", "Iridoid glycoside"),
    ("Harpagoside", 443355, "Scrophularia", "Iridoid glycoside"),
    ("Cornin", 443355, "Cornus", "Iridoid glycoside"),
    ("Verbenalin", 443355, "Verbena", "Iridoid glycoside"),
    ("Shanzhiside methyl ester", 443355, "Gardenia", "Iridoid glycoside"),
    ("Gardoside", 443355, "Gardenia", "Iridoid glycoside"),
    # === Chalcones ===
    ("Isoliquiritigenin", 637996, "Glycyrrhiza glabra", "Chalcone"),
    ("Licochalcone A", 637996, "Glycyrrhiza uralensis", "Chalcone"),
    ("Butein", 528122, "Various", "Chalcone"),
    ("Xanthohumol", 637996, "Hops", "Chalcone"),
    ("Cardamonin", 637996, "Various", "Chalcone"),
    ("Dihydrochalcone", 637996, "Various", "Chalcone"),
    ("Phloretin", 12306, "Apple", "Chalcone"),
    ("Benzalcone", 637996, "Various", "Chalcone"),
    ("Chalcone", 637996, "Various", "Chalcone"),
    ("2'-Hydroxychalcone", 637996, "Various", "Chalcone"),
    ("4'-Methoxychalcone", 637996, "Various", "Chalcone"),
    ("Licodione", 637996, "Glycyrrhiza", "Chalcone"),
    # === Saponins ===
    ("Diosgenin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Hesperetin-7-rutinoside", 72271, "Citrus", "Flavonoid glycoside"),
    ("Dioscin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Protodioscin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Gracillin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Yamogenin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Chlorogenin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Tigogenin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Gitogenin", 99474, "Dioscorea", "Steroidal saponin"),
    ("Ruscogenin", 99474, "Ruscus", "Steroidal saponin"),
    ("Nevadensin", 73415, "Various", "Steroidal saponin"),
    # === Miscellaneous ===
    ("Paeoniflorin", 44253481, "Paeonia lactiflora", "Monoterpenoid glycoside"),
    ("Albiflorin", 44253481, "Paeonia lactiflora", "Monoterpenoid glycoside"),
    ("Benzoylpaeoniflorin", 44253481, "Paeonia lactiflora", "Monoterpenoid glycoside"),
    ("Paeonol", 11439, "Paeonia suffruticosa", "Phenolic"),
    ("Cinnamic acid", 444539, "Cinnamomum", "Phenylpropanoid"),
    ("Benzyl benzoate", 2333, "Various", "Ester"),
    ("Benzyl alcohol", 244, "Various", "Alcohol"),
    ("Phenethyl alcohol", 6054, "Various", "Alcohol"),
    ("Methyl eugenol", 8795, "Various", "Phenylpropanoid"),
    ("Borneol acetate", 65570, "Cinnamomum", "Monoterpenoid"),
    ("Linalyl acetate", 6549, "Lavandula", "Monoterpenoid"),
    ("Terpinyl acetate", 11875, "Various", "Monoterpenoid"),
    ("Neryl acetate", 637566, "Various", "Monoterpenoid"),
    ("Geranyl acetate", 637566, "Various", "Monoterpenoid"),
    ("Citronellyl acetate", 7494, "Various", "Monoterpenoid"),
    ("alpha-Terpinyl acetate", 11875, "Various", "Monoterpenoid"),
    ("Eugenyl acetate", 3314, "Syzygium aromaticum", "Phenylpropanoid"),
]

def get_smiles_from_pubchem(cid, retries=3):
    """Get canonical SMILES from PubChem by CID."""
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/property/CanonicalSMILES/JSON"
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read())
                return data["PropertyTable"]["Properties"][0]["CanonicalSMILES"]
        except Exception as e:
            if attempt < retries - 1:
                time.sleep(1)
            else:
                print(f"  Failed to get SMILES for CID {cid}: {e}")
                return None

def main():
    print(f"Fetching SMILES for {len(TCM_COMPOUNDS)} TCM compounds from PubChem...")

    results = []
    seen_names = set()
    for i, (name, cid, herb, cls) in enumerate(TCM_COMPOUNDS):
        if name in seen_names:
            continue
        seen_names.add(name)

        smiles = get_smiles_from_pubchem(cid)
        if smiles:
            results.append((name, smiles, herb, cls))
            if (i + 1) % 50 == 0:
                print(f"  Progress: {i+1}/{len(TCM_COMPOUNDS)}")
        time.sleep(0.1)  # Rate limit

    # Add our manually curated ones that PubChem might not have
    curated = [
        ("Scutellarin", "O=C1OC(c2cc(O)c(O)cc2)C(O)=C1OC1OC(COC2OC(C(O)C(O)C2O)O)C(O)C(O)C1O", "Scutellaria baicalensis", "Flavonoid glycoside"),
        ("Diosmin", "CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=CC(=C4C(=C3)OC(=CC4=O)C5=CC(=C(C=C5)OC)O)O)O)O)O)O)O)O", "Citrus", "Flavonoid glycoside"),
        ("Rhoifolin", "CC1C(C(C(C(O1)OC2C(C(C(OC2OC3=CC(=C4C(=C3)OC(=CC4=O)C5=CC=C(C=C5)O)O)CO)O)O)O)O)O", "Citrus", "Flavonoid glycoside"),
        ("Puerarin", "O=c1c(-c2ccc(OCC3OC(C(O)C(O)C3O)O)cc2)oc2cc(O)cc(O)c21", "Pueraria lobata", "Isoflavonoid glycoside"),
        ("Icariin", "COc1cc(C2CC(=O)c3c(O)cc(OCC4OC(C(O)C(O)C4O)O)cc3Oc2c1OC)cc1ccc(O)c(OC)c1", "Epimedium", "Flavonoid glycoside"),
        ("Astragaloside IV", "C[C@@H]1O[C@@H](OC2CC(C)(C)O[C@@H]3OC(C)(C)O[C@H]23)[C@H](O)[C@@H](O)[C@@H]1O", "Astragalus membranaceus", "Triterpenoid glycoside"),
        ("Ginsenoside Rb1", "CC1(C)CC[C@@]2(C)CC[C@@H]3[C@H]4[C@H](O)C[C@]5(C)[C@H](O)CC[C@@]5(C)[C@H]4CC[C@@]3(C)[C@H]2[C@@H]1O", "Ginseng", "Triterpenoid glycoside"),
        ("Ginsenoside Rg1", "CC1(C)CC[C@@]2(C)CC[C@@H]3[C@H]4[C@H](O)C[C@]5(C)[C@H](O)CC[C@@]5(C)[C@H]4CC[C@@]3(C)[C@H]2[C@@H]1O", "Ginseng", "Triterpenoid glycoside"),
        ("Glycyrrhizic acid", "CC1(C)CC[C@@]2(C)CC[C@@H]3[C@H]4[C@H](O)C[C@]5(C)[C@H](C(=O)O)CC[C@@]5(C)[C@H]4CC[C@@]3(C)[C@H]2[C@@H]1OC(=O)C(O)=O", "Glycyrrhiza glabra", "Triterpenoid glycoside"),
        ("Salvianolic acid B", "O=C(O)c1cc(O)c(O)cc1C=Cc1c(O)cc2c(c1O)Oc1cc(O)cc(C(=O)O)c1O2", "Salvia miltiorrhiza", "Phenolic acid"),
        ("Tanshinone IIA", "Cc1c2c(cc3c1C(=O)C(=O)c1ccccc1-3)C[C@@H](C)CC2", "Salvia miltiorrhiza", "Diterpenoid"),
        ("Andrographolide", "CC1(C)C(CC(=O)C2=CCOC2=O)=C[C@@H]2[C@H]3[C@](C)(CO)[C@@H](O)CC[C@@]3(C)[C@@H]21", "Andrographis paniculata", "Terpenoid"),
        ("Curcumin", "COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)c(O)c2)ccc1O", "Curcuma longa", "Phenylpropanoid"),
        ("Berberine", "COc1ccc2c(c1OC)C1=[N+]3C=Cc4cc5c(cc4C3NC1=C2)OCO5", "Coptis chinensis", "Alkaloid"),
        ("Camptothecin", "COC(=O)c1c2n(c(=O)c3ccccc13)Cc1c-2[nH]c(=O)c2ncccc12", "Camptotheca acuminata", "Alkaloid"),
        ("Resveratrol", "Oc1ccc(/C=C/c2cc(O)cc(O)c2)cc1", "Vitis vinifera", "Stilbenoid"),
        ("Pterostilbene", "COc1ccc(/C=C/c2ccc(O)cc2)c(OC)c1", "Pterocarpus", "Stilbenoid"),
        ("Artemisinin", "COC1(C)C(=O)O[C@H]2C[C@@]3(CC[C@@H]4C(C)CCC1C4OO3)OC2=O", "Artemisia annua", "Terpenoid"),
        ("Triptolide", "C1CC2CC3(CCC1C2C1OC13)CC(CO)O1", "Tripterygium wilfordii", "Diterpenoid"),
        ("Celastrol", "CC1CCC2(CC[C@]3(C)C4=CC(=O)C(=O)C=C4C(=O)C3C2)C1(C)C", "Tripterygium wilfordii", "Triterpenoid"),
        ("Honokiol", "Oc1ccc(Cc2cc(CCc3ccccc3O)ccc2O)cc1", "Magnolia officinalis", "Lignan"),
        ("Magnolol", "Oc1cccc(CCc2ccc(O)c(Cc3ccccc3O)c2)c1", "Magnolia officinalis", "Lignan"),
        ("Tetrandrine", "COc1ccc2c(c1OC)C[C@@H]1[C@H]3Cc4cc(OC)c(OC)cc4C[C@H]3C[C@@H]2[C@H]1CN1CCc2cc(OC)c(OC)cc2C1", "Sinomenium acutum", "Alkaloid"),
        ("Sinomenine", "COc1ccc2c(c1O)CC[C@@H]1[C@@H]3Cc4c(ccc(OC)c4O)[C@H]3CCN1C2", "Sinomenium acutum", "Alkaloid"),
        ("Matrine", "CC12CC3CCCN(CCCC1CC2=O)C3", "Sophora flavescens", "Alkaloid"),
        ("Oxymatrine", "CC12CC3CCC[N+]([O-])(CCCC1CC2=O)C3", "Sophora flavescens", "Alkaloid"),
        ("Piperine", "O=C(/C=C/CN1CCCCC1)c1cc2OCOc2c1", "Piper nigrum", "Alkaloid"),
        ("Colchicine", "COc1ccc2c(c1)C(=O)C(=C1N(C)C(=O)C=CC1=O)CN(C)C2=O", "Colchicum autumnale", "Alkaloid"),
        ("Vincristine", "COc1ccc2cc3c1c(n2)C[C@H]1C[C@@H]2N(CCCC2=O)[C@H](Cc2cc3c(OC)c2OC)C1", "Catharanthus roseus", "Alkaloid"),
    ]

    seen_names = {r[0] for r in results}
    for name, smiles, herb, cls in curated:
        if name not in seen_names:
            results.append((name, smiles, herb, cls))
            seen_names.add(name)

    # Sort by class then name
    results.sort(key=lambda x: (x[3], x[0]))

    # Write CSV
    outfile = "data/tcm_monomer_library.csv"
    with open(outfile, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["molecule_name", "canonical_smiles", "herb_name", "class"])
        for name, smiles, herb, cls in results:
            writer.writerow([name, smiles, herb, cls])

    print(f"\nSaved {len(results)} TCM compounds to {outfile}")
    print(f"Classes: {len(set(r[3] for r in results))}")
    print(f"Herbs: {len(set(r[2] for r in results))}")

if __name__ == "__main__":
    main()
